# Generated by Django 5.2.16 on 2026-08-16 10:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("departments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "register_number",
                    models.CharField(
                        help_text="College register number — must be unique across all students",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
                ("batch", models.CharField(help_text="e.g. 2023-2027", max_length=20)),
                (
                    "academic_year",
                    models.CharField(
                        help_text="Current academic year e.g. 2026-27", max_length=20
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1st Year"),
                            (2, "2nd Year"),
                            (3, "3rd Year"),
                            (4, "4th Year"),
                        ],
                        help_text="Current year of study",
                    ),
                ),
                (
                    "semester",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Semester 1"),
                            (2, "Semester 2"),
                            (3, "Semester 3"),
                            (4, "Semester 4"),
                            (5, "Semester 5"),
                            (6, "Semester 6"),
                            (7, "Semester 7"),
                            (8, "Semester 8"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        blank=True,
                        help_text="Section A, B, C etc.",
                        max_length=5,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("graduated", "Graduated"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="students",
                        to="departments.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
                "db_table": "students",
                "ordering": ["department", "batch", "section", "name"],
                "indexes": [
                    models.Index(
                        fields=["department", "batch", "year"],
                        name="students_departm_99d267_idx",
                    ),
                    models.Index(
                        fields=["department", "section"],
                        name="students_departm_6f431a_idx",
                    ),
                ],
            },
        ),
    ]
