# Generated by Django 5.2.16 on 2026-08-16 10:58

import django.db.models.deletion
import django.utils.timezone
import excel_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("departments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExcelImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to=excel_manager.models.excel_upload_path),
                ),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "column_mapping",
                    models.JSONField(
                        blank=True,
                        help_text="Maps system field names to Excel column headers",
                        null=True,
                    ),
                ),
                ("error_log", models.JSONField(blank=True, null=True)),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("imported_rows", models.PositiveIntegerField(default=0)),
                ("duplicate_rows", models.PositiveIntegerField(default=0)),
                ("invalid_rows", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PREVIEW", "Awaiting Column Mapping"),
                            ("PROCESSING", "Processing"),
                            ("DONE", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="excel_imports",
                        to="departments.department",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="excel_imports",
                        to="accounts.staffprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Excel Import",
                "verbose_name_plural": "Excel Imports",
                "db_table": "excel_imports",
                "ordering": ["-created_at"],
            },
        ),
    ]
