# Generated by Django 5.2.16 on 2026-08-16 10:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("departments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("LOGIN_FAILED", "Login Failed"),
                            ("UPLOAD", "File Upload"),
                            ("DOWNLOAD", "File Download"),
                            ("UPDATE", "Record Updated"),
                            ("DELETE", "Record Deleted"),
                            ("EXCEL_IMPORT", "Excel Import"),
                            ("EXCEL_EXPORT", "Excel Export"),
                            ("USER_CREATE", "User Created"),
                            ("USER_DEACTIVATE", "User Deactivated"),
                            ("SUBJECT_ASSIGN", "Subject Assigned"),
                            ("PERMISSION_CHANGE", "Permission Changed"),
                            ("PASSWORD_CHANGE", "Password Changed"),
                            ("VIEW", "Record Viewed"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "object_type",
                    models.CharField(
                        blank=True,
                        help_text="Model name e.g. Resource, Student",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        blank=True,
                        help_text="PK of the affected object",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="departments.department",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "db_table": "audit_logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="audit_logs_user_id_88267f_idx",
                    ),
                    models.Index(
                        fields=["department", "timestamp"],
                        name="audit_logs_departm_9dc1e0_idx",
                    ),
                    models.Index(
                        fields=["action", "timestamp"],
                        name="audit_logs_action_474804_idx",
                    ),
                ],
            },
        ),
    ]
