# Generated by Django 5.2.16 on 2026-08-16 10:58

import django.db.models.deletion
import django.utils.timezone
import resources.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("departments", "0001_initial"),
        ("subjects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Bootstrap icon class e.g. bi-file-earmark-text",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Resource Category",
                "verbose_name_plural": "Resource Categories",
                "db_table": "resource_categories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="e.g. Data Structures Unit 1 Notes", max_length=300
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "semester",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Semester 1"),
                            (2, "Semester 2"),
                            (3, "Semester 3"),
                            (4, "Semester 4"),
                            (5, "Semester 5"),
                            (6, "Semester 6"),
                            (7, "Semester 7"),
                            (8, "Semester 8"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "unit",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Unit 1"),
                            (2, "Unit 2"),
                            (3, "Unit 3"),
                            (4, "Unit 4"),
                            (5, "Unit 5"),
                        ],
                        help_text="Unit number (optional, mainly for Notes)",
                        null=True,
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to=resources.models.resource_upload_path),
                ),
                ("file_name", models.CharField(editable=False, max_length=255)),
                (
                    "file_size",
                    models.PositiveBigIntegerField(
                        editable=False, help_text="Size in bytes"
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        editable=False, help_text="MIME type", max_length=100
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resources",
                        to="subjects.academicyear",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resources",
                        to="departments.department",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resources",
                        to="subjects.subject",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_resources",
                        to="accounts.staffprofile",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resources",
                        to="resources.resourcecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resource",
                "verbose_name_plural": "Resources",
                "db_table": "resources",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["department", "subject"],
                        name="resources_departm_adc62a_idx",
                    ),
                    models.Index(
                        fields=["department", "category"],
                        name="resources_departm_207aa7_idx",
                    ),
                ],
            },
        ),
    ]
